"""1_tables_created

Revision ID: 20bd0073986e
Revises: 
Create Date: 2024-07-28 16:19:18.783233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bd0073986e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expenses_id', table_name='expenses')
    op.create_index(op.f('ix_expenses_expense_id'), 'expenses', ['expense_id'], unique=False)
    op.drop_index('ix_splits_id', table_name='splits')
    op.create_index(op.f('ix_splits_split_id'), 'splits', ['split_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_splits_split_id'), table_name='splits')
    op.create_index('ix_splits_id', 'splits', ['split_id'], unique=False)
    op.drop_index(op.f('ix_expenses_expense_id'), table_name='expenses')
    op.create_index('ix_expenses_id', 'expenses', ['expense_id'], unique=False)
    # ### end Alembic commands ###
