"""add to cart table updated

Revision ID: 0cf2fa1943e9
Revises: 0f74274d9577
Create Date: 2024-05-20 15:56:56.464001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf2fa1943e9'
down_revision: Union[str, None] = '0f74274d9577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('add_to_cart_product_name_key', 'add_to_cart', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('add_to_cart_product_name_key', 'add_to_cart', ['product_name'])
    # ### end Alembic commands ###
