"""2_tables created

Revision ID: 24d932e27473
Revises: be19c558378b
Create Date: 2024-07-14 17:55:13.450317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d932e27473'
down_revision: Union[str, None] = 'be19c558378b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('children', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('children', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
