"""2_tables created

Revision ID: 596954324a3f
Revises: cf0c020f3ba6
Create Date: 2024-07-15 12:00:38.933182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596954324a3f'
down_revision: Union[str, None] = 'cf0c020f3ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('profile_photo', sa.String(), nullable=True))
    op.add_column('parents', sa.Column('country', sa.String(), nullable=True))
    op.add_column('parents', sa.Column('pincode', sa.String(), nullable=True))
    op.drop_column('parents', 'zipcode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('zipcode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('parents', 'pincode')
    op.drop_column('parents', 'country')
    op.drop_column('parents', 'profile_photo')
    # ### end Alembic commands ###
